import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar/navbar'
import PredictionPlayground from '@/components/Playground/prediction'
import ModalProvider from '@/providers/modelprovider'
import SupabaseProvider from '@/providers/SupabaseProvider'
import getData from '@/actions/getData'
import Script from 'next/script'

import Home from '../components/Playground/prediction'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider />
        <SupabaseProvider>
          <div className='mt-[25px]'>
            <NavBar>
              {children}
            </NavBar>
          </div>
        </SupabaseProvider>
      </body>
    </html>
  )
}
